# Generated by Django 3.1.1 on 2020-12-24 20:51

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999-999-9999'. Up to 12 digits allowed.", regex='\\d{3}-\\d{3}-\\d{4}')])),
                ('email', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999-999-9999'. Up to 12 digits allowed.", regex='\\d{3}-\\d{3}-\\d{4}')])),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('ext', models.CharField(blank=True, max_length=10, null=True)),
                ('avaya_login', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(choices=[('S', 'Specialist'), ('A', 'Analyst'), ('L', 'Leader')], max_length=1)),
                ('team', models.CharField(choices=[('S', 'Specialist'), ('A', 'Analyst'), ('L', 'Leader')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Specialists',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('important', models.BooleanField(blank=True, null=True)),
                ('update', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('pto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lateArrival', models.IntegerField(blank=True, null=True)),
                ('earlyDepart', models.IntegerField(blank=True, null=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('acw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('acw_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aht', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('call', models.IntegerField(blank=True, null=True)),
                ('ticket', models.IntegerField(blank=True, null=True)),
                ('aux_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avail_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('staffed_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.specialist')),
            ],
            options={
                'verbose_name_plural': 'Statistics',
                'ordering': ['specialist'],
                'unique_together': {('specialist', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QA_Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qa_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('qa_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qa_ticket', models.CharField(blank=True, max_length=100, null=True)),
                ('qa_comment', models.TextField(blank=True, max_length=500, null=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.specialist')),
            ],
            options={
                'verbose_name': 'QA Score',
                'verbose_name_plural': 'QA Scores',
                'unique_together': {('specialist', 'qa_ticket')},
            },
        ),
    ]
