# Generated by Django 3.1.1 on 2020-12-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='role',
            field=models.CharField(choices=[('S', 'Specialist'), ('A', 'Analyst'), ('L', 'Leader')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='team',
            field=models.CharField(choices=[('S', 'Specialist'), ('A', 'Analyst'), ('L', 'Leader')], default='S', max_length=2),
        ),
    ]
