# Generated by Django 3.1.1 on 2020-12-29 17:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20201224_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='email',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Email must be entered in the format: 'email@domain.com'. At least 5-50 characters allowed. ", regex='.{1,}@[^.]{1,}')]),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='team',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('CC', 'Call Center')], default='IT', max_length=2),
        ),
    ]
