# Generated by Django 3.1.1 on 2021-01-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210110_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('CC', 'Call Center')], default='IT', max_length=20),
        ),
    ]
