# Generated by Django 3.1.1 on 2021-01-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210110_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='update',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
